name: monad-http
version: 0.2.0.0
synopsis: A class of monads which can do http requests
description: A class of monads which can do http requests
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-monad-http
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2, GHC==7.10.3
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall

dependencies:
- base                >=4.7      && <4.10
- base-compat         >=0.6.0    && <0.10
- bytestring          >=0.10.0.4 && <0.12
- exceptions          >=0.8.0.2  && <0.9
- http-client         >=0.4.18.1 && <0.5
- http-client-tls     >=0.2.2    && <0.3
- http-types          >=0.8.6    && <0.10
- monad-logger        >=0.3.13.2 && <0.4
- monadcryptorandom   >=0.6.1    && <0.8
- MonadRandom         >=0.3.0.2  && <0.5
- operational         >=0.2.3.2  && <0.3
- mtl                 >=2.1.3.1  && <2.3
- text                >=1.2.0.6  && <1.3
- transformers        >=0.3.0.0  && <0.6
- transformers-compat >=0.4.0.3  && <0.6

library:
  source-dirs: src
